## В данном ноутбуке посмотрим, с какими данными мы будем работать

Импортируем библиотеки

In [1]:
import pandas as pd
import numpy as np

Загружаем исходные данные (наш датасет)

In [9]:
df = pd.read_csv('../raw_files/ab_testing.csv')

Проверим первые строки таблицы, посмотрим как выглядит наш датасет

In [10]:
df.head()

   User ID Group  Page Views  Time Spent Conversion   Device          Location
0    14292     B           3         424         No   Mobile  Northern Ireland
1    11682     A           9         342         No   Mobile          Scotland
2    19825     A           2         396         No  Desktop  Northern Ireland
3    16080     B           4         318         No  Desktop             Wales
4    18851     A           1         338        Yes  Desktop          Scotland

Определим количество строк и столбцов в таблице

In [16]:
print('Строки:', df.shape[0], ', Столбцы:', df.shape[1])

Строки: 5000 , Столбцы: 7

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User ID     5000 non-null   int64
 1   Group       5000 non-null   object
 2   Page Views  5000 non-null   int64
 3   Time Spent  5000 non-null   int64
 4   Conversion  5000 non-null   object
 5   Device      5000 non-null   object
 6   Location    5000 non-null   object
dtypes: int64(3), object(4)
memory usage: 273.6+ KB

## В датасете есть следующие признаки:

- **User ID** — идентификатор пользователя  
- **Group** — принадлежность к контрольной или тестовой группе  
- **Page Views** — количество просмотренных страниц  
- **Time Spent** — время нахождения на сайте (в секундах)  
- **Conversion** — факт совершения целевого действия  
- **Device** — тип устройства пользователя  
- **Location** — регион Великобритании

Посмотрим статистические характеристики всех признаков

In [20]:
df.describe(include = 'all')

,User ID,Group,Page Views,Time Spent,Conversion,Device,Location
count,5000.000000,5000,5000.000000,5000.000000,5000,5000,5000
unique,NaN,2,NaN,NaN,2,2,4
top,NaN,A,NaN,NaN,No,Desktop,Scotland
freq,NaN,2519,NaN,NaN,4515,2538,1281
mean,14925.159000,NaN,7.537600,242.512600,NaN,NaN,NaN
std,2869.153773,NaN,4.022465,118.254153,NaN,NaN,NaN
min,10001.000000,NaN,1.000000,40.000000,NaN,NaN,NaN
25%,12456.250000,NaN,4.000000,137.000000,NaN,NaN,NaN
50%,14858.500000,NaN,8.000000,243.000000,NaN,NaN,NaN
75%,17379.750000,NaN,11.000000,346.000000,NaN,NaN,NaN
max,19995.000000,NaN,14.000000,449.000000,NaN,NaN,NaN

Посмотрим уникальные значения категориальных признаков

In [22]:
categorical_columns = ['Group', 'Conversion', 'Device', 'Location']

for col in categorical_columns:
    print(f"{col}:")
    print(df[col].unique())

Group:
['B' 'A']
Conversion:
['No' 'Yes']
Device:
['Mobile' 'Desktop']
Location:
['Northern Ireland' 'Scotland' 'Wales' 'England']

Посмотрим на распределение контрольной и экспериментальной групп

In [23]:
df['Group'].value_counts()

Group
A    2519
B    2481
Name: count, dtype: int64